# Generated by Django 4.0.6 on 2022-11-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_desc', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_image', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
